name: 'NPM Publish'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write

jobs:
  publish:
    name: 'Build and Publish to NPM'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Get version bump type
        id: version-bump
        run: |
          # Get the latest commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)

          # Determine version bump type based on commit message
          if echo "$COMMIT_MSG" | grep -qE "^(feat|feature)(\(.+\))?:"; then
            echo "bump-type=minor" >> $GITHUB_OUTPUT
            echo "Detected feat: commit, bumping minor version"
          else
            echo "bump-type=patch" >> $GITHUB_OUTPUT
            echo "Detected non-feat commit, bumping patch version"
          fi

      - name: Bump version
        run: npm version ${{ steps.version-bump.outputs.bump-type }} --no-git-tag-version

      - name: Commit version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json
          git commit -m "Bump version [skip ci]"
          git push

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
